sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - "6"
  - "7"
  - "node"

install:
  - yarn
  - yarn add --dev coveralls

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

jobs:
  include:
    - stage: test
      script:
        - npm rebuild node-sass
        - yarn ci:travis
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - stage: deploy
      script:
       - yarn clean

cache:
  yarn: true
  directories:
    - node_modules
