sudo: required
dist: trusty
jobs:
  include:
  - stage: test
    node_js: '7'
    addons:
      chrome: stable
    language: node_js
    install:
    - yarn
    - yarn add --dev coveralls
    before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
    script:
    - npm rebuild node-sass
    - yarn ci:travis
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    cache:
      yarn: true
      directories:
      - node_modules
  - stage: deploy
    node_js: '7'
    language: node_js
    install:
    - yarn
    script:
      - yarn semantic-release pre
      - yarn build:aot
      - yarn semantic-release post
    branches:
      only: [master]
    cache:
      yarn: true
      directories:
      - node_modules
    deploy:
      provider: releases
      api_key:
        secure: ck+xTFbo7grQ/jVg5cB09247H5xufeZdR8774/uUs8DxNw5m6XGSt9ONG3TN2r5IzMrWUFpCO5BDGZGQl2m/h+JRl8WBsH2+I3+14zfmVWI0Fi+U+U4V0u7Sxq0VqkEgrl8ji87Fz+AhyDVumGj1aOaYNd6QXQes7YapfeDzynPpXUbNX4o0d91XiV6o1dOtPbmnQSqJE8ArVCiPlKCBgoeXaKOTXrHED8tkuyMPGkJilSoE2MbNKGAGacP4h8xGCkZNR7+aAsXofzcDddzbChfwPunWg93BKa1bJNxQ5vlSqwVca6aM3oAWcDlpCRwcaA0tq+ROQyowNJ+5kzjGkAo5nx8c0qE6UTNwi2KZOU2AQ0bwulaWM4hRwQVpKEo1pxxAMwTf4PUlaTLIYUX6K+nbaYraGVVKYmL5AEpHKHi//mVPGR6oD+iAsXaDPi+xE6CycrReh9Q/Iezgz2WqN0rJ9G56PGSxNUTjN1roXccnMkCUcr3at2eIuf4KCqa/Q75mXZOi/PQXd4ub9AnZGCPODS5F8oqNDLYARneGdXqoDA5kEoLkR7C+BQIM3a9dQc5lffsrcjygn3TMfYaXw+k8UAdxYy1jV64Op0x+40iwfrUWGHwRYQytHb2rAcJbK99jXYvc6A8a9Vqrq2V32W+BdRcqHilJ+abhhc46ycY=
      file_glob: true
      skip_cleanup: true
      file: dist/*
      on:
        branch: master
        repo: Joatin/jsound-client

